[package]
name = "google-authenticator-export"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.3"

[build-dependencies]
prost-build = "0.13.3"

[profile.release]
strip = true
lto = true
